      LOGICAL FUNCTION DECCHK (STRING)
      IMPLICIT NONE

*     FORMAL_PARAMETERS:
      CHARACTER*(*) STRING

*     Local variables
      INCLUDE 'rdndec.gin'
      INTEGER TTYPE, IB, IE, NERR, NWAR
      SAVE

      CALL RDERRI (' ',0,0,.FALSE.,.FALSE.)

      CALL PARSWORD (STRING,TTYPE,IB,IE,NERR,NWAR)

      DECCHK = NERR.EQ.0.AND.(TTYPE.EQ.TFLOAT.OR.TTYPE.EQ.TINTEG)

      RETURN
      END
